/// File generated by FlutterFire CLI.
/// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

//// Default [FirebaseOptions] for use with your Firebase apps.
///
//// Example:
//// ```dart
//// import 'firebase_options.dart';
//// /// ...
//// await Firebase.initializeApp(
////   options: DefaultFirebaseOptions.currentPlatform,
//// );
//// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoI4gwEq5s1Wf5MQ2srCeTAVWL5Gvaxjo',
    appId: '1:783501479359:android:3437f0ec8beed12555a50a',
    messagingSenderId: '783501479359',
    projectId: 'drivehandlerapi',
    storageBucket: 'drivehandlerapi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFh41uljaRJVj8hMqCDUXLA1zTSb2FJ8',
    appId: '1:783501479359:ios:d002e01d68bcf08855a50a',
    messagingSenderId: '783501479359',
    projectId: 'drivehandlerapi',
    storageBucket: 'drivehandlerapi.appspot.com',
    androidClientId: '783501479359-bku2saa9re7semefpaif90q41dh509mo.apps.googleusercontent.com',
    iosClientId: '783501479359-ghup1efhoa6fd9t91nptfls8l0g4akci.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
