// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbdqR8PHB8ejrDNBw7siway-wmY0yDcs',
    appId: '1:438147421441:android:7f46634b53deb04afa3700',
    messagingSenderId: '438147421441',
    projectId: 'drivehandlerapp',
    storageBucket: 'drivehandlerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIWwp1wsg6Ht1JQl-Ku3UcAy9-qDKJBFo',
    appId: '1:438147421441:ios:9a1ad34808ef47fcfa3700',
    messagingSenderId: '438147421441',
    projectId: 'drivehandlerapp',
    storageBucket: 'drivehandlerapp.appspot.com',
    androidClientId: '438147421441-239qphgis8v1egbfe06prcq9jgh5uhcd.apps.googleusercontent.com',
    iosClientId: '438147421441-n4hmqqej7eh1qr4jcbupn8pakqadk0ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
